env:
  browser: true
  commonjs: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars: [
    error,
    {
      vars: all,
      args: all,
      varsIgnorePattern: "[iI]gnored",
      argsIgnorePattern: "[iI]gnored"
    }
  ]
parserOptions:
  sourceType: module
